services:
  postgres:
    image: postgres:15
    container_name: lista_compras_db
    networks:
      - lista_compras_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lista_compras
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: guipiri/lista-de-compras:latest
    container_name: lista_compras_app
    networks:
      - lista_compras_network
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lista_compras
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: lista_compras_cloudflared
    networks:
      - lista_compras_network
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN} --url http://app:3000
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  lista_compras_network:
    driver: bridge
